[package]
name = "ru_practice"
version = "0.1.0"
authors = ["brianch <brianch@users.noreply.github.com>"]

[dependencies]
curl = "0.4.8"
serde_json = "1.0"
serde = "1.0.26"
serde_derive = "1.0.26"
kuchiki = "0.6.0"
gio = "0.3.0"

[dependencies.gtk]
version = "0.3.0"
features = ["v3_10"]
